### ISSUE TITLE
Crash vom Adapter

### ISSUE THREAD

**Issue by JackDaniel007** [TA2k/ioBroker.mihome-cloud#15]
miio.0
2024-01-12 08:54:39.897	error	Error: undefined is not a valid state value at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17) at Miio._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49) at Miio.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21) at Miio.miioAdapterUpdateState (/opt/iobroker/node_modules/iobroker.miio/build/main.js:142:18) at Controller.<anonymous> (/opt/iobroker/node_modules/iobroker.miio/build/main.js:441:30) at Controller.emit (node:events:517:28) at DeviceClass.<anonymous> (/opt/iobroker/node_modules/iobroker.miio/build/lib/miio.js:181:22) at DeviceClass.emit (node:events:517:28) at DeviceClass.attributeUpdate (/opt/iobroker/node_modules/iobroker.miio/build/lib/Devices/device.js:169:14) at DeviceClass.propertyUpdated (/opt/iobroker/node_modules/iobroker.miio/build/lib/Devices/device.js:292:22)

miio.0
2024-01-12 08:54:39.891	error	unhandled promise rejection: undefined is not a valid state value

miio.0
2024-01-12 08:54:39.890	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by TA2k** [comment]
Sieht nach miio adapter aus nicht mihome-cloud

**Comment by JackDaniel007** [comment]
shit falsch abgebogen, sorry
