### ISSUE TITLE
axios time out erhöhen? 

### ISSUE THREAD

**Issue by Grothesk242** [TA2k/ioBroker.mihome-cloud#9]
Ich bekomme regelmäßig nachstehende Meldungen im Log. Kann man ggf. das timeout an der Stelle erhöhen?

```
2023-04-02 04:23:28.489  - error: mihome-cloud.0 (618526) /miotspec/prop/get
2023-04-02 04:23:28.490  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
2023-04-02 04:23:28.659  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
    at Function.AxiosError.from (/opt/iobroker/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:512:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:524:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.req.emit (/opt/iobroker/node_modules/iobroker.mihome-cloud/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:84:16)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
2023-04-02 05:53:49.955  - error: mihome-cloud.0 (618526) /miotspec/prop/get
2023-04-02 05:53:49.956  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
2023-04-02 05:53:49.958  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
    at Function.AxiosError.from (/opt/iobroker/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:512:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:524:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.req.emit (/opt/iobroker/node_modules/iobroker.mihome-cloud/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:84:16)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
2023-04-02 06:35:01.122  - error: mihome-cloud.0 (618526) /miotspec/prop/get
2023-04-02 06:35:01.123  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
2023-04-02 06:35:01.125  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
    at Function.AxiosError.from (/opt/iobroker/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:512:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:524:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.req.emit (/opt/iobroker/node_modules/iobroker.mihome-cloud/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:84:16)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
2023-04-02 06:36:24.322  - error: mihome-cloud.0 (618526) /miotspec/prop/get
2023-04-02 06:36:24.323  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
2023-04-02 06:36:24.324  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
    at Function.AxiosError.from (/opt/iobroker/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:512:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:524:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.req.emit (/opt/iobroker/node_modules/iobroker.mihome-cloud/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:84:16)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
2023-04-02 07:00:00.259  - error: mihome-cloud.0 (618526) /miotspec/prop/get
2023-04-02 07:00:00.259  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
2023-04-02 07:00:00.262  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
    at Function.AxiosError.from (/opt/iobroker/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:512:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:524:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.req.emit (/opt/iobroker/node_modules/iobroker.mihome-cloud/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:84:16)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
2023-04-02 08:13:15.001  - error: mihome-cloud.0 (618526) /miotspec/prop/get
2023-04-02 08:13:15.002  - error: mihome-cloud.0 (618526) Error: socket hang up
2023-04-02 08:13:15.004  - error: mihome-cloud.0 (618526) Error: socket hang up
    at Function.AxiosError.from (/opt/iobroker/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:512:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:524:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.req.emit (/opt/iobroker/node_modules/iobroker.mihome-cloud/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:84:16)
    at TLSSocket.socketOnEnd (node:_http_client:519:9)
    at TLSSocket.emit (node:events:524:35)
2023-04-02 08:22:59.420  - warn: mihome-cloud.0 (618526) Error getting Status of the device via Plugin for Ventilator (90211825) with {"id":0,"method":"get_prop","accessKey":"IOS00026747c5acafc2","params":[]}
2023-04-02 08:22:59.421  - warn: mihome-cloud.0 (618526) {"code":-3,"error":{"code":-3,"message":"timeout"},"exe_time":0,"id":8195745,"message":"timeout","net_cost":0,"ot_cost":0}
2023-04-02 08:36:00.089  - info: host.chet instance system.adapter.iceroad.0 started with pid 642883
2023-04-02 08:36:02.327  - info: iceroad.0 (642883) starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.iceroad, node: v19.8.1, js-controller: 5.0.1-alpha.0-20230330-e0b409fe
2023-04-02 08:36:03.071  - info: iceroad.0 (642883) Terminated (NO_ERROR): Without reason
2023-04-02 08:36:03.617  - info: host.chet instance system.adapter.iceroad.0 terminated with code 0 (NO_ERROR)
2023-04-02 10:23:58.596  - error: mihome-cloud.0 (618526) /miotspec/prop/get
2023-04-02 10:23:58.597  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
2023-04-02 10:23:58.600  - error: mihome-cloud.0 (618526) Error: read ETIMEDOUT
    at Function.AxiosError.from (/opt/iobroker/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:512:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:524:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.req.emit (/opt/iobroker/node_modules/iobroker.mihome-cloud/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:84:16)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
```

**Comment by TA2k** [comment]
Ist das ein China account? Kommt das auch mit der github version

**Comment by Grothesk242** [comment]
Ja, der Account spricht Chinesisch.
Version aus GitHub:
***@***.*** (git+ssh://
***@***.***/TA2k/ioBroker.mihome-cloud.git#e3bfab06b04163faacaa72edd7190f8e30252e60
)

TA2k ***@***.***> schrieb am Mo., 3. Apr. 2023, 07:42:
